### ISSUE TITLE
flip180 does not report to side from side

### ISSUE THREAD

**Issue by SirGoodenough** [JJPro/CTP-R01-converter#1]
See here for details:

 https://github.com/Koenkk/zigbee2mqtt/issues/15652#issuecomment-1398909796

Also, as a request, can the from side always be reported for all actions, even if the from is the same as the current action side?
You see if you gently flip the cube 90 or 180, you can get it to not register the flip action, but it will still register a for instance slide action where the current side matches the slide action side, but the from side registers where it was last.  The original cube would do this, and it is used as another 'secret' trigger action on my HA blueprints.  I do have to generate the from for best results, but having the from side code always report does give the cube more things it can do...

**Comment by JJPro** [comment]
Check the latest commit, exposes and action payload are streamlined. 
See [this table](https://github.com/JJPro/CTP-R01-converter/wiki/Supported%20Actions) for all action payloads (e.g. flip180 payload now contains `action_from_side`)
